<a href="https://colab.research.google.com/github/Isabel160609/Cuadernos-colab-Pyton/blob/main/Copia_de_Ejercicios_vectores_y_matrices_nivel_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Ejercicio 1: El Historial de Compras (Filtro de Datos)**
Contexto Real: Una tienda en línea quiere saber qué clientes gastaron más de $50 en su última compra para enviarles un cupón.

Tu Reto: Crea un vector con los montos: [25, 55, 10, 75, 48, 100]. Usa NumPy para filtrar y mostrar solo los gastos mayores a 50.

In [ ]:
import numpy as np
importes=np.array([25, 55, 10, 75, 48, 100])
mayores50 = importes[importes>50]
print(mayores50)

[ 55  75 100]


**Ejercicio 2: El Conversor de Monedas (Operación Escalar)**

Contexto Real: Tienes una lista de precios en dólares y necesitas convertirlos a euros para tu web en Europa (asume que $1 USD = 0.92 EUR).

Tu Reto: Multiplica un vector de precios en dólares por el factor de conversión usando una sola operación de NumPy (sin usar bucles for).

In [ ]:
import numpy as np
precios_dolares = np.array([10, 20, 30, 40, 50])
factor_conversion = 0.92
precios_euros = precios_dolares * factor_conversion
print(precios_euros)

[ 9.2 18.4 27.6 36.8 46. ]


**Ejercicio 3: Rendimiento de Acciones (Operaciones entre Vectores)**

Contexto Real: Quieres calcular las ganancias netas de 4 acciones de bolsa. Tienes el precio de venta y el precio de compra.

Tu Reto: Resta el vector de precios_compra al vector de precios_venta para obtener el beneficio neto de cada una.

In [ ]:
import numpy as np
precios_venta = np.array([100, 80, 120, 90])
precios_compra = np.array([80, 60, 100, 7])
beneficios_netos = precios_venta - precios_compra
print(beneficios_netos)

**Ejercicio 4: Recomendación de Películas (Producto Punto / Similitud)**

Contexto Real: Netflix analiza tus gustos. Si te gustan las películas de Acción (1) y Comedia (0), tu vector es [1, 0]. Una película nueva tiene etiquetas [0.8, 0.2].

Tu Reto: Investiga cómo calcular el "producto punto" (dot product) en NumPy entre tu perfil y la película para medir qué tan compatible es contigo.

In [ ]:
import numpy as np
perfil_usuario = np.array([1, 0])
etiquetas_pelicula = np.array([0.8, 0.2])
producto_punto = np.dot(perfil_usuario, etiquetas_pelicula)
print(producto_punto)

0.8


**Ejercicio 5: Sensor de Temperatura (Estadística Básica)**

Contexto Real: Un sensor IoT registra la temperatura de un invernadero cada hora.

Tu Reto: Con un vector de 10 temperaturas, calcula automáticamente la temperatura media, la máxima y la mínima usando funciones de NumPy.

In [ ]:
import numpy as np
temperaturas=[28,29,30,31,32,33,34,35,36,37]
temperatura_media = np.mean(temperaturas)
temperatura_maxima = np.max(temperaturas)
temperatura_minima = np.min(temperaturas)
print(temperatura_media)
print(temperatura_maxima)
print(temperatura_minima)

32.5
37
28


**Ejercicio 6: Calificaciones de la Escuela (Creación y Selección)**

Contexto Real: Una matriz donde cada fila es un estudiante y cada columna es una materia (Matemáticas, Historia, Ciencia).

Tu Reto: Crea la matriz, extrae las notas del segundo estudiante (toda la fila) y luego extrae solo las notas de Ciencia (toda la última columna). Recuerda que en programación empezamos a contar desde 0.

In [ ]:
import numpy as np
estudiantes=["marta", "Isa", "Bea"]
asignaturas= ["Matemáticas", "Historia", "Ciencia"]

notas= (
    [8, 9, 7],
    [7, 8, 9],
    [9, 7, 8])
notas=np.array(notas)
print(f"Todas las notas  son: {notas}")
print(f"Las notas de Isa son: {notas[1]}")
print(f"Las notas de ciencias son: {notas[:,2]}")

Todas las notas  son: [[8 9 7]
 [7 8 9]
 [9 7 8]]
Las notas de Isa son: [7 8 9]
Las notas de ciencias son: [7 9 8]


**Ejercicio 7: Inventario de Tiendas (Suma por Ejes)**

Contexto Real: Tienes 3 tiendas (filas) que venden 4 tipos de productos (columnas). Necesitas saber cuántos productos totales vende cada tienda.

Tu Reto: Suma los elementos de la matriz a lo largo de las filas (investiga el parámetro axis en NumPy).

In [ ]:
import numpy as np
ventas=(
    [10, 15, 20, 25],
    [20, 25, 30, 35],
    [30, 35, 40, 45])
ventas=np.array(ventas)
print(f"Las ventas totales son: {ventas.sum(axis=1)}")



Las ventas totales son: [ 70 110 150]


**Ejercicio 8: Filtro de Fotografía / Modo Oscuro (Modificar Matrices)**

Contexto Real: En computación, una imagen digital en blanco y negro es una matriz de píxeles (donde 0 es negro y 255 es blanco).

Tu Reto: Crea una matriz que represente una imagen pequeña de 3x3 píxeles oscuros. Multiplícala por un factor para "subir el brillo".

In [ ]:
import numpy as np
imagen3x3=(
    [0, 0, 0],
    [0, 0, 0],
    [0, 0, 0])
imagen3x3=np.array(imagen3x3)
factor=2
print(f"\nImagen original: \n{imagen3x3}")
imagen_brillo=imagen3x3*factor
print(f"\nSi todos los píxeles son cero, multiplicar por un factor no cambiará nada (0 * factor = 0).")
print(f"\nImagen con brillo(multiplicando por factor 2): \n{imagen_brillo}")

imagen3x3B=(
    [2, 5, 3],
    [1, 5, 7],
    [2, 5, 6])
imagen3x3B=np.array(imagen3x3B)
factor=2
print(f"\nImagen original: \n{imagen3x3B}")
imagen_brilloB=imagen3x3B*factor
print("\nSi no todos los píxeles son cero, podemos multiplicar por un factor y cambiará.")
print(f"\nImagen con brillo(multiplicando por factor 2): \n{imagen_brilloB}")

# --- Respuesta a la pregunta del usuario sobre el brillo de una imagen con píxeles cero ---
# Si todos los píxeles son cero, multiplicar por un factor no cambiará nada (0 * factor = 0).
# Para 'subir el brillo' de una imagen completamente oscura, necesitas sumar un valor constante a cada píxel.

imagen_negra = np.array(
    [[0, 0, 0],
     [0, 0, 0],
     [0, 0, 0]])

valor_brillo_adicional = 50 # Un valor que simula 'subir el brillo'

imagen_con_brillo = imagen_negra + valor_brillo_adicional
print(f"\nImagen original (negra):\n{imagen_negra}")
print("\ncuando todos los píxeles son cero, podemos sumar por un factor para que cambie.")
print(f"\nImagen con brillo (sumando un valor constante):\n{imagen_con_brillo}")


Imagen original: 
[[0 0 0]
 [0 0 0]
 [0 0 0]]

Si todos los píxeles son cero, multiplicar por un factor no cambiará nada (0 * factor = 0).

Imagen con brillo(multiplicando por factor 2): 
[[0 0 0]
 [0 0 0]
 [0 0 0]]

Imagen original: 
[[2 5 3]
 [1 5 7]
 [2 5 6]]

Si no todos los píxeles son cero, podemos multiplicar por un factor y cambiará.

Imagen con brillo(multiplicando por factor 2): 
[[ 4 10  6]
 [ 2 10 14]
 [ 4 10 12]]

Imagen original (negra):
[[0 0 0]
 [0 0 0]
 [0 0 0]]

cuando todos los píxeles son cero, podemos sumar por un factor para que cambie.

Imagen con brillo (sumando un valor constante):
[[50 50 50]
 [50 50 50]
 [50 50 50]]


**Ejercicio 9: El Analista de Ventas Mensuales (Transposición de Matrices)**

Contexto Real: Recibes datos donde las filas son meses y las columnas son productos, pero tu jefe te pide el reporte al revés: filas de productos y columnas de meses.

Tu Reto: Aplica la operación de "transposición" a tu matriz para rotar los datos de forma inmediata.

In [ ]:
import numpy as np
ventas=(
    [10, 15, 20, 25],
    [20, 25, 30, 35],
    [30, 35, 40, 45])
ventas=np.array(ventas)
print(f"Ventas: \n{ventas}")
print(f"\nVentas transpuestas: \n{ventas.T}")

Ventas: 
[[10 15 20 25]
 [20 25 30 35]
 [30 35 40 45]]

Ventas transpuestas: 
[[10 20 30]
 [15 25 35]
 [20 30 40]
 [25 35 45]]


**Ejercicio 10: Red Neuronal Simple (Multiplicación de Matrices)**

Contexto Real: En Inteligencia Artificial, las neuronas reciben datos de entrada (matriz de datos) y los multiplican por "pesos" de importancia (matriz de pesos) para dar una predicción.

Tu Reto: Multiplica una matriz de datos de tamaño 2x3 por una matriz de pesos de tamaño 3x2 usando la multiplicación de matrices de NumPy (@ o np.dot).

In [ ]:
import numpy as np
datos = (
    [3,4,6],
    [1,5,2])
datos=np.array(datos)
print(f"Datos: \n{datos}")
pesos = (
    [1,3],
    [2,3],
    [4,2]
)
pesos = np.array(pesos)
print(f"\nPesos: \n{pesos}")

prediccion = datos @ pesos
print(f"\nMultiplicación de matrices con @: \n{prediccion}")
prediccion2 = np.dot(datos, pesos)
print(f"\nMultiplicación de matrices con np.dot: \n{prediccion2}")



Datos: 
[[3 4 6]
 [1 5 2]]

Pesos: 
[[1 3]
 [2 3]
 [4 2]]

Multiplicación de matrices con @: 
[[35 33]
 [19 22]]

Multiplicación de matrices con np.dot: 
[[35 33]
 [19 22]]
